use_frameworks!

platform :ios, '13.0'

target 'Stagehand_Example' do
  pod 'Stagehand', :path => '../'

  target 'Stagehand-UnitTests' do
    inherit! :search_paths

    pod 'StagehandTesting/iOSSnapshotTestCase', :path => '../'
    pod 'StagehandTesting/SnapshotTesting', :path => '../'

    # SnapshotTesting dropped support for building with Xcode 10 in 1.8.0, so pin the version to 1.7.0 in order to
    # run our tests against Xcode 10.
    pod 'SnapshotTesting', '= 1.7.0'
  end

  target 'Stagehand-PerformanceTests' do
    inherit! :search_paths

    pod 'Stagehand', :path => '../'
  end
end

install! 'cocoapods', disable_input_output_paths: true
