language: objective-c
jobs:
  - osx_image: xcode11.3
    env: DEST='platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro'
  - osx_image: xcode10.3
    env: DEST='platform=iOS Simulator,OS=12.4,name=iPhone Xs'
  - osx_image: xcode10.3
    env: DEST='platform=iOS Simulator,OS=11.4,name=iPhone X'
  - osx_image: xcode10.3
    env: DEST='platform=iOS Simulator,OS=10.3.1,name=iPhone 7'
install:
  - bundle install --gemfile=Example/Gemfile
  - bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Stagehand.xcworkspace -scheme "Stagehand Demo App" -sdk iphonesimulator -destination $DEST ONLY_ACTIVE_ARCH=NO | xcpretty
  - bundle exec --gemfile=Example/Gemfile pod lib lint
