language: objective-c
jobs:
  - osx_image: xcode11.3
    env: ACTIONS="xcode,pod-lint";PLATFORM="iOS_13"
  - osx_image: xcode10.3
    env: ACTIONS="xcode,pod-lint";PLATFORM="iOS_12"
  - osx_image: xcode10.3
    env: ACTIONS="xcode,pod-lint";PLATFORM="iOS_11"
  - osx_image: xcode10.3
    env: ACTIONS="xcode,pod-lint";PLATFORM="iOS_10"
  - osx_image: xcode11.3
    env: ACTIONS="swift-package";PLATFORM="iOS_13"
install:
  - bundle install --gemfile=Example/Gemfile
  - bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Stagehand.xcworkspace -scheme "Stagehand Demo App" -sdk iphonesimulator -destination "$DEST" ONLY_ACTIVE_ARCH=NO | xcpretty
  - bundle exec --gemfile=Example/Gemfile pod lib lint
branches:
  only:
  - master
