name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  pod-lint:
    name: Pod Lint
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Lint podspecs
        run: bundle exec --gemfile=Example/Gemfile pod lib lint --verbose --fail-fast --include-podspecs=Stagehand.podspec StagehandTesting.podspec
  spm:
    name: SPM Build
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          # select minimum supported Xcode version
          sudo xcode-select -s /Applications/Xcode_14.3.1.app
          # TODO: add SPM test target, for now just run build on all products.
          xcodebuild build \
            -scheme Stagehand-Package \
            -sdk iphonesimulator16.4 \
            -destination "OS=16.4,name=iPhone 13 Pro"

  xcode-build:
    name: Xcode Build
    runs-on: macOS-14
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.app
      - name: Build and Test
        run: |
          # run tests on the example app
          xcodebuild test \
            -workspace Example/Stagehand.xcworkspace \
            -scheme "Stagehand Demo App" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,OS=18.0,name=iPhone 16 Pro"
      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Test Results
          path: .build/derivedData/**/Logs/Test/*.xcresult
