name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  xcode-build:
    name: Xcode Build
    runs-on: macOS-11
    strategy:
      matrix:
        platform: ['iOS_15', 'iOS_13']
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Prepare Simulator Runtimes
        run: Scripts/github/prepare-simulators.sh ${{ matrix.platform }}
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Build and Test
        run: Scripts/build.swift xcode ${{ matrix.platform }} `which xcpretty`
      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Test Results
          path: .build/derivedData/**/Logs/Test/*.xcresult
  pod-lint:
    name: Pod Lint
    runs-on: macOS-11
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Lint Stagehand Podspec
        run: bundle exec --gemfile=Example/Gemfile pod lib lint --verbose --fail-fast Stagehand.podspec
      - name: Lint StagehandTesting Podspec
        run: bundle exec --gemfile=Example/Gemfile pod lib lint --verbose --fail-fast --include-podspecs=Stagehand.podspec StagehandTesting.podspec
  spm:
    name: SPM Build
    runs-on: macOS-11
    strategy:
      matrix:
        platform: ['iOS_13']
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Prepare Simulator Runtimes
        run: Scripts/github/prepare-simulators.sh ${{ matrix.platform }}
      - name: Build
        run: Scripts/build.swift spm ${{ matrix.platform }}
  bazel:
    name: Bazel
    runs-on: macOS-13
    steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
        - name: Build
          run: bazel build //...
